const Parser = require("rss-parser");
const { WebClient } = require("@slack/web-api");

const parser = new Parser();
const slack = new WebClient(process.env.SLACK_BOT_TOKEN);

// ─── RSS FEED SOURCES ────────────────────────────────────────────────────────
// Add or remove feeds relevant to your intelligence/geospatial/OSInt domain
const RSS_FEEDS = [
  "https://feeds.feedburner.com/TheHackersNews",               // cyber/intel
  "https://www.bellingcat.com/feed/",                          // OSINT investigations
  "https://www.c4isrnet.com/arc/outboundfeeds/rss/",           // C4ISR / defence
  "https://rss.janes.com/content/janes/all/news/en",           // Jane's defence
  "https://feeds.feedburner.com/SettlersOfCatan",              // placeholder - replace
];

// Number of articles to pick per feed
const ARTICLES_PER_FEED = 2;

// ─── FETCH PRESS ─────────────────────────────────────────────────────────────
async function fetchArticles() {
  const articles = [];

  for (const url of RSS_FEEDS) {
    try {
      const feed = await parser.parseURL(url);
      const items = feed.items.slice(0, ARTICLES_PER_FEED);
      for (const item of items) {
        articles.push({
          title: item.title || "Untitled",
          summary: item.contentSnippet || item.content || "",
          link: item.link || "",
          source: feed.title || url,
          date: item.pubDate || "",
        });
      }
      console.log(`  ✓ Fetched ${items.length} articles from: ${feed.title || url}`);
    } catch (err) {
      console.error(`  ✗ Failed to fetch ${url}:`, err.message);
    }
  }

  return articles;
}

// ─── GENERATE USE CASE VIA CLAUDE ────────────────────────────────────────────
async function generateUseCase(articles) {
  const articleSummaries = articles
    .map((a, i) => `[${i + 1}] "${a.title}" (${a.source})\n${a.summary}`)
    .join("\n\n");

  const prompt = `You are a senior product strategist for ARKEM Intelligence Platform — a geospatial device-tracking and intelligence analysis suite used by intelligence professionals.

ARKEM's two core products are:
- MDS: a geospatial device-tracking platform (built on Kepler.gl) for visualising and investigating device intelligence
- Neon: a mission-based operational platform for managing AI alias personas in outbound and inbound intelligence operations (OSINT, HUMINT support, social engineering campaigns)

Below are this week's press articles from the intelligence, OSINT, geospatial, and defence domains:

${articleSummaries}

Based on these articles, identify ONE compelling, concrete use case where ARKEM (either MDS, Neon, or both) could have been applied. 

Format your response exactly like this:

## 🛰 Weekly ARKEM Use Case

**Inspired by:** [article title(s) and source]

**Scenario:**
[2-3 sentences describing a realistic operational scenario that mirrors what the press covers]

**How ARKEM helps:**
[3-4 bullet points. Be specific: name MDS or Neon, reference real features like alias deployment, RASCLS compliance, device flagging, Kepler.gl layers, Query Builder, Multi-Tracer, etc. where relevant]

**Intelligence value:**
[1-2 sentences on the strategic or tactical outcome this enables]

Keep it grounded and credible — written for an intelligence analyst or mission commander audience, not a sales deck.`;

  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": process.env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model: "claude-sonnet-4-20250514",
      max_tokens: 1000,
      messages: [{ role: "user", content: prompt }],
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`Claude API error: ${response.status} — ${err}`);
  }

  const data = await response.json();
  return data.content.find((b) => b.type === "text")?.text || "";
}

// ─── POST TO SLACK ────────────────────────────────────────────────────────────
async function postToSlack(useCase, articles) {
  const sourceLinks = articles
    .slice(0, 5)
    .map((a) => `• <${a.link}|${a.title}> — ${a.source}`)
    .join("\n");

  const blocks = [
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: useCase,
      },
    },
    { type: "divider" },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Press sources used this week:*\n${sourceLinks}`,
      },
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `Generated by ARKEM Press Bot • ${new Date().toLocaleDateString("en-GB", {
            weekday: "long",
            year: "numeric",
            month: "long",
            day: "numeric",
          })}`,
        },
      ],
    },
  ];

  await slack.chat.postMessage({
    channel: process.env.SLACK_CHANNEL_ID,
    text: "🛰 Weekly ARKEM Use Case — from this week's press",
    blocks,
  });

  console.log(`  ✓ Posted to Slack channel: ${process.env.SLACK_CHANNEL_ID}`);
}

// ─── MAIN ─────────────────────────────────────────────────────────────────────
async function generateAndPost() {
  try {
    console.log("  → Fetching RSS articles...");
    const articles = await fetchArticles();

    if (articles.length === 0) {
      console.error("  ✗ No articles fetched. Aborting.");
      return;
    }

    console.log(`  → Generating use case from ${articles.length} articles...`);
    const useCase = await generateUseCase(articles);

    console.log("  → Posting to Slack...");
    await postToSlack(useCase, articles);

    console.log("  ✓ Done.");
  } catch (err) {
    console.error("  ✗ Error in generateAndPost:", err);
  }
}

module.exports = { generateAndPost };
